### ISSUE TITLE
Add docs on snapshotting plugins 

### ISSUE THREAD

**Issue by mablae** [prooph/event-store-symfony-bundle#3]
```
your_snapshot_plugin:
       class: Prooph\Snapshotter\SnapshotPlugin
       factory: [Acme\EventStoreSnapshotPluginFactory, createPlugin]
       arguments: ['@prooph_service_bus.your_command_bus']
       tags:
             - { name: prooph_event_store.your_event_store.plugin }

```
From gitter: (@SandroKeil)
@itcraftsmanpl You can register the snapshotter as a plugin https://github.com/prooph/service-bus-symfony-bundle/blob/master/doc/getting_started.md
