### ISSUE TITLE
How to use SingleStreamStrategy?

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-symfony-bundle#40]
I'm trying to enable SingleStreamStrategy to fix performance issues in projections (see https://github.com/proophsoftware/es-emergency-call/issues/5 for details).

For now I'm unable to get it working. EventStore still makes one stream per aggregate instead of per aggregate type. Here is my current configuration:

```yaml
services:
    Prooph\EventStore\Pdo\PostgresEventStore:
        arguments: ['@messageFactory', '@eventStoreConnection', '@stream_strategy']

    stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\PostgresSingleStreamStrategy
```

In the documentation I found a link to [this example](https://github.com/prooph/proophessor-do/blob/master/scripts/create_event_stream.php) to initialize the streams. This creates one more stream in the database but the EventStore is still creating new streams for every new aggregate. Also the example is confusing. Shouldn't I create one stream for each aggregate type instead of just one stream?

**Comment by enumag** [comment]
Ok it seems it needs to be configured on each repository definition as well:

```yaml
prooph_event_store:
    stores:
        acme_store:
            event_store: Prooph\EventStore\Pdo\MysqlEventStore
            repositories:
                todo_list:
                    repository_class: Prooph\ProophessorDo\Infrastructure\Repository\EventStoreUserCollection
                    aggregate_type: Prooph\ProophessorDo\Model\User\User
                    aggregate_translator: prooph_event_sourcing.aggregate_translator
                    # I was missing this line.
                    one_stream_per_aggregate: false
```

Now however eventstore only uses that one stream I created based on the example script linked above. All events from all aggregate types are mixed in this stream. How can I separate them to one stream per aggregate type?
