### ISSUE TITLE
How to register event-store plugins such as Metadata enricher

### ISSUE THREAD

**Issue by ambroisemaupate** [prooph/event-store-symfony-bundle#58]
http://docs.getprooph.org/event-store/event_store_plugins.html

I try to to register a metadata enricher for authenticated events:

```yaml
services:
  app.metadata_enricher:
    class: "App\\EventStore\\MetadataEnricher\\AuthenticatedEventMetadataEnricher"
    autowire: true
    autoconfigure: true

  app.metadata_enricher_plugin:
    class: "Prooph\\EventStore\\Metadata\\MetadataEnricherPlugin"
    arguments:
      - '@app.metadata_enricher'
    calls:
      - method: attachToEventStore
        arguments:
          - '@app.event_store.default'
```
But event-store configuration does not allow plugin registering such as service-bus does.

**Comment by ambroisemaupate** [comment]
Ok, after looking at services compilation, I found it out 👍 

I needed to tag my MetadataEnricher with `prooph_event_store.%name%.metadata_enricher`:

```yaml
app.metadata_enricher:
    class: "App\\EventStore\\MetadataEnricher\\AuthenticatedEventMetadataEnricher"
    autowire: true
    autoconfigure: true
    tags:
       - { name: 'prooph_event_store.default_store.metadata_enricher' }
```

**Comment by webdevilopers** [comment]
Thanks for this solution @ambroisemaupate . Do you know if this works with `"prooph/event-store": "6.6.1"` too?!

**Comment by webdevilopers** [comment]
I'm currently trying to migrate this to *v6.6.1*.

```yml
prooph_service_bus:
    event_buses:
        acme_event_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
                - 'event_enricher.plugin'

services:
    prooph_event_store_bus_bridge.event_enricher:
        class: Acme\Infrastructure\EventStore\MetadataEnricher\EventEnricherPlugin
        tags:
            - { name: 'prooph_event_store.default_store.plugin' }
```

It looks like the Plugin is registered but I get:
```
Type error: Argument 1 passed to Prooph\ServiceBus\MessageBus::utilize() must implement interface Prooph\Common\Event\ActionEventListenerAggregate, instance of Acme\Infrastructure\EventStore\MetadataEnricher\EventEnricherPlugin given
```

My Plugin is based on the example by @prolic :
* https://www.sasaprolic.com/2015/10/adding-custom-metadata-to-domain-events.html

I also tried switching to the `ActionEventListenerAggregate` interface. But when adding the "attach" method in Sascha's example I get *Attempted to call an undefined method named "trackHandler"*:

```php
    public function attach(ActionEventEmitter $emitter)
    {
        //Attach with a low priority, so that a potential message translator has done its job already
        $this->trackHandler($emitter->attachListener(CommandBus::EVENT_INITIALIZE, [$this, 'onInitialize'], -1000));
    }
```

I Guess I'm mixing up a lot of versions here. Maybe someone can help. No need to re-open this as an issue since it is not linked to the current version.
