### ISSUE TITLE
Repository autowiring doesn't work

### ISSUE THREAD

**Issue by siwymilek** [prooph/event-store-symfony-bundle#65]
I can't autowire repositories – is this an issue or deliberate action?
Here is my event store configuration:

```
prooph_event_store:
    stores:
        user_store:
            event_store: 'prooph_event_store.pdo_mysql_event_store'
            repositories:
                App\Infrastructure\User\Repository\EventStoreUserRepository:
                    aggregate_type: App\Domain\User\Model\User
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'
```

And here is the error:

> Cannot autowire service "App\Infrastructure\User\Repository\EventStoreUserRepository": argument "$aggregateType" of method "Prooph\EventSourcing\Aggregate\AggregateRepository::__construct()" references class "Prooph\EventSourcing\Aggregate\AggregateType" but no such service exists.

**Comment by RSalo** [comment]
I have the same problem.

**Comment by superbull** [comment]
@siwymilek @RSalo 
I come across the same problem. It takes me 1 day to fix.

Change your config to something like below will work.
Assume your Repository interface is `App\Domain\Model\User\UserRepository`, change it to what ever you type hinted.

```
prooph_event_store:
    stores:
        user_store:
            event_store: 'prooph_event_store.pdo_mysql_event_store'
            repositories:
                user_repository:
                    repository_class: App\Infrastructure\User\Repository\EventStoreUserRepository
                    aggregate_type: App\Domain\User\Model\User
                    aggregate_translator: 'prooph_event_sourcing.aggregate_translator'

services:
    # change below to your type hinted type
    App\Domain\Model\User\UserRepository: '@user_repository'
```
